version: "3"

services:
  app:
    user: $UID:$GID
    build:
      context: .
    ports:
      - "8000:8888"
    volumes:
      #mount all the code in app directory in local to app directory of conatiner
      - ./app/:/app
    working_dir: /app
    command: > 
      sh -c "jupyter notebook  --ip='*' --port=8888 --no-browser --allow-root"